using System;
using System.Collections.Generic;
using System.Linq;

namespace HerbiSoft.Core.SampleDtos.Dtos 
{
	/// <summary>
	/// Auto-Generated by DtoGenerator.tt - do not modify as changes will be overridden
	/// </summary>
	public class CourseDtoBase
	{
        public Int32 Id { get; set; }
        public String Title { get; set; }
        public String Description { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public TeacherDtoBase Teacher { get; set; }
	}
}

