using System;
using System.Collections.Generic;
using System.Linq;

namespace HerbiSoft.Core.SampleDtos.Dtos 
{
	/// <summary>
	/// Auto-Generated by DtoGenerator.tt - do not modify as changes will be overridden
	/// </summary>
	public class PersonDtoBase
	{
        public Int32 Id { get; set; }
        public String FirstName { get; set; }
        public String LastName { get; set; }
	}
}

