using System;
using System.Collections.Generic;
using System.Linq;

namespace HerbiSoft.Core.SampleDtos.Dtos 
{
	/// <summary>
	/// Auto-Generated by DtoGenerator.tt - do not modify as changes will be overridden
	/// </summary>
	public class StudentDtoBase
	{
        public List<CourseDtoBase> Courses { get; set; }
	}
}

